### PR TITLE
Update ServiceRouteMapper.cs

### LINKED ISSUE #3: Add backward TLS compatibility
Add backward TLS compatibility.

### PR DESCRIPTION
**Pull request by david-poindexter**
Resolves #3

### CODE REVIEW

**Comment by davidjrh** [comment]
Merging this PR, would allow Tls 1.0 or Tls 1.1 if Tls 1.2 is not available, that breaks the initial intention of "forcing" the outbound connections to be Tls1.2 (or fail intentionally). I'm not sure if would be better to add a setting on the web.config to allow this new behavior, to don't break the original objective.

Thoughts?

**Comment by david-poindexter** [comment]
Good point.  For our use cases, we like this fail-safe in practice.  It lowers the risk of implementation.  It is not always known whether or not all outbound requests will actually work with a strict TLS 1.2 enforcement.

**Comment by davidjrh** [comment]
Yeah, I understand. The original use case was that just by dropping this assembly on the bin folder, was a way to ensure that any outbound connection was in TLS 1.2 needed by some regulations and compliance. I would like to avoid changing that default behavior. Can you change the PR to allow overriding the default Tls 1.2 value by reading the Tls allowed versions from an app setting?

**Comment by david-poindexter** [comment]
@davidjrh you have valid points.  I think maybe we just close this PR and focus on this for DNN Platform.  See dnnsoftware/Dnn.Platform#2603

**Pull request closed without merging**
